### PR TITLE
Closes #146: migrating to kubebuilder format and SDK 0.19.x

### LINKED ISSUE #146: Upgrade to Operator SDK latest 0.x version
Seems that 1.0.0 might have some issues and we are about to launch 0.3 in a couple weeks, won’t have time to upgrade and run all the tests. 

Let’s stick with the latest 0.x for now to remain with the structure that we have today.

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <ricardozanini@gmail.com>

We will start migrating to the new [kubebuilder format required by SDK 0.19.x](https://v0-19-x.sdk.operatorframework.io/docs/golang/project_migration_guide/).

TODO:

- [ ] Migrate e2e to [Envtest](https://v0-19-x.sdk.operatorframework.io/docs/golang/references/env-test-setup)
- [ ] Update documentation
- [ ] Migrate Integration test CI (disabled for now)
- [ ] Smoke tests on an Kubernetes cluster

Closes #146

### CODE REVIEW

**Comment by ricardozanini** [comment]
@Kaitou786 this may interest you.

**Comment by Kaitou786** [comment]
> @Kaitou786 this may interest you.

Thanks @ricardozanini , one doubt thought why not directly to 1.0.x?, Seeing this format I can't find the difference between the format of 0.19.x and 1.0.x ?

**Comment by ricardozanini** [comment]
> > @Kaitou786 this may interest you.
> 
> Thanks @ricardozanini , one doubt thought why not directly to 1.0.x?, Seeing this format I can't find the difference between the format of 0.19.x and 1.0.x?
> See this [migration guide](https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/)

TBH I didn't know that they changed the format and break the SDK on 0.19.x. I was surprised when I saw the guide. I'll figure how to upgrade to 0.19.x for now since the SDK core hasn't changed that much. 1.x is target for the next version. I'd rather wait for their patches on 1.x first.

**Comment by ricardozanini** [comment]
Let's migrate directly to 1.0.0. See #140

**Pull request closed without merging**
