### PR TITLE
The PR aims to improve the handling of WATCH_NAMESPACE param when ins…

### PR DESCRIPTION
**Pull request by Kaitou786**
…talling from OLM.

OLM doesn't set any env var for us, so earlier whenever someone installs the operator in a specific namespace
The operator would still run in cluster wide, since the WATCH_NAMESPACE var was not found.

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
The integration check is supposed to fail due to their changes, right @Kaitou786 ?

**Comment by Kaitou786** [comment]
@ricardozanini  Well not sure, it could be due to the bug we have right now in our CI system.
The current operator version is set to 0.5.0 on master. But we already have 0.5.0 released on [nexus-operator community operators](https://github.com/operator-framework/community-operators/tree/master/community-operators/nexus-operator-m88i) and we copy this as defined [here](https://github.com/m88i/nexus-operator/blob/main/hack/ci/operator-ensure-manifest.sh#L31-L37) Which is leading to the [error](https://github.com/m88i/nexus-operator/pull/202/checks?check_run_id=1686478244#step:11:291 about having 2 CSVs). 
The solution would be to bump our master to next version.

**Comment by ricardozanini** [comment]
@Kaitou786 indeed. I haven't seen the logs, shame on me. I'll send a PR to upgrade to 0.6.0. Many thanks!

**Review by LCaparelli — APPROVED** [review]
Thanks @Kaitou786!

**Comment by ricardozanini** [comment]
> @Kaitou786 indeed. I haven't seen the logs, shame on me. I'll send a PR to upgrade to 0.6.0. Many thanks!

Waiting for OLM to merge our 0.5.0 PR.

**Comment by Kaitou786** [comment]
Okay, no worries :)

**Comment by LCaparelli** [comment]
I bumped the version to 0.6.0 on #206, this should be ready to go once that's merged

**Review by ricardozanini — APPROVED** [review]

**Pull request merged**
