### PR TITLE
Add networking E2E tests

### LINKED ISSUE #75: Add networking e2e tests
It would be nice to have e2e tests for the multiple networking scenarios we support.

### PR DESCRIPTION
**Pull request by LCaparelli**
Notable changes:

  - add networking E2E tests
  - add structured test case logic to allow the addition of test cases
  without deeper knowledge of what goes on in testing
  - add documentation about creating E2E tests
  - add an increased default timeout for the e2e tests (15m)

Fix #75 

Signed-off-by: Lucas Caparelli <lucas.caparelli112@gmail.com>

### CODE REVIEW

**Comment by LCaparelli** [comment]
Setting the Image Pull Policy to "IfNotPresent" could speed up the tests. Blocking this on #97

**Comment by ricardozanini** [comment]
I'll review once the WIP label disappears! =D

**Comment by LCaparelli** [comment]
Alright, checks passed, WIP label off. Let me know your thoughts @ricardozanini @Kaitou786 :grin:

**Comment by Kaitou786** [comment]
Looks really good to me!

**Pull request merged**
