### PR TITLE
Remove deprecated commands from github actions workflow

### PR DESCRIPTION
**Pull request by sowmiyamuthuraman**
Fixes https://github.com/m88i/nexus-operator/issues/167

### CODE REVIEW

**Comment by sowmiyamuthuraman** [comment]
@ricardozanini I have removed the usage of `add-path` from the `integration-test workflow`. In `Lint` workflow, neither set-env nor add-path is used, but i could still see the warnings. am i missing something?

**Comment by Kaitou786** [comment]
> @ricardozanini I have removed the usage of `add-path` from the `integration-test workflow`. In `Lint` workflow, neither set-env nor add-path is used, but i could still see the warnings. am i missing something?

@sowmiyamuthuraman can you tell us which warning are you seeing? :)

**Review by Kaitou786 — APPROVED** [review]

**Comment by sowmiyamuthuraman** [comment]
> > @ricardozanini I have removed the usage of `add-path` from the `integration-test workflow`. In `Lint` workflow, neither set-env nor add-path is used, but i could still see the warnings. am i missing something?
> 
> @sowmiyamuthuraman can you tell us which warning are you seeing? :)

I could see the usage of set-env, add-path warning in the `Lint workflow` https://github.com/m88i/nexus-operator/actions/runs/288716981

**Comment by LCaparelli** [comment]
Thanks for your contribution @sowmiyamuthuraman, it's looking great!

> @ricardozanini I have removed the usage of add-path from the integration-test workflow. In Lint workflow, neither set-env nor add-path is used, but i could still see the warnings. am i missing something?

Yup, these are coming from the golangci-lint action we're using, which seems to still be using the deprecated action. Right now, we done everything we can on our end. I have filed #169 to handle these remaining warnings, so I'm merging this PR with what we can deal with. :smile:

**Review by LCaparelli — APPROVED** [review]

**Pull request merged**
