### PR TITLE
cov test

### PR DESCRIPTION
**Pull request by Kaitou786**

### CODE REVIEW

**Comment by Kaitou786** [comment]
@LCaparelli @ricardozanini I opened the same PR on my [forked repo](https://github.com/Kaitou786/nexus-operator/pull/6) and it is comparing there with the latest commit.

**Comment by Kaitou786** [comment]
Closing this one as it was only a test

**Comment by ricardozanini** [comment]
I noticed that some times the report is not uploaded to codecov, I believe we need to always double check and sometimes rerun the job to upload it again.

**Comment by Kaitou786** [comment]
@ricardozanini  Do you think we shoulf consider using the GH action by codecov for uploading the reults?

**Comment by ricardozanini** [comment]
> @ricardozanini Do you think we shoulf consider using the GH action by codecov for uploading the reults?

Yes!

**Comment by Kaitou786** [comment]
Okay, I'll send a PR for doing this :-)

**Pull request closed without merging**
