### PR TITLE
codecov test

### PR DESCRIPTION
**Pull request by Kaitou786**

### CODE REVIEW

**Comment by Kaitou786** [comment]
@ricardozanini let's see here if the codecov sends the report without the action :-)

**Comment by ricardozanini** [comment]
Looks like it doesn't 😆

**Comment by ricardozanini** [comment]
@Kaitou786 try adding just the `config.yaml` file in this PR without the action.

**Comment by Kaitou786** [comment]
@ricardozanini added `codecov.yml` without the action looks like it didn't send the report without that action.

**Comment by ricardozanini** [comment]
Perfect! I’m closing this one and will merge the other as soon as @LCaparelli approves it.

**Pull request closed without merging**
