### PR TITLE
Comment only when change in codecov report

### PR DESCRIPTION
**Pull request by Kaitou786**

### CODE REVIEW

**Comment by Kaitou786** [comment]
According the documentation the comment should not be there, even if commented before it should be deleted as coverage is same [See](https://docs.codecov.io/docs/pull-request-comments#requiring-changes)

**Comment by ricardozanini** [comment]
Well, let's merge either way. I don't think this option would cause a harm.

**Comment by Kaitou786** [comment]
@ricardozanini the olm starts failing. I think could be related to the testing image which was recently updated: https://quay.io/repository/operator-framework/operator-testing?tag=latest&tab=tags. We are having this same error on kogito-cloud-operator

**Comment by ricardozanini** [comment]
> @ricardozanini the olm starts failing. I think could be related to the testing image which was recently updated: https://quay.io/repository/operator-framework/operator-testing?tag=latest&tab=tags. We are having this same error on kogito-cloud-operator

I noticed, I opened #124 
Will fix it in a couple hours.

**Comment by LCaparelli** [comment]
Shall we merge this @ricardozanini?

**Comment by Kaitou786** [comment]
@ricardozanini do you think we can have similar approach we are using on the kogito-cloud-operator?

**Comment by Kaitou786** [comment]
> > @ricardozanini do you think we can have similar approach we are using on the kogito-cloud-operator?
> 
> I think that we could skip running tests on docs changes, but I believe we already have that set, right?

Currenly we've set the following config:
```
on:
  pull_request:
  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "CONTRIBUTING.md"
      - "examples/**"
      - "LICENSE"
      - "LICENSE_NOTICE"
      - "Makefile"
      - ".github/ISSUE_TEMPLATE/**"
    branches:
      - master
```
Due to which for every PR, which is created we run the tests no matter where the changes. For push, we've ignored those changes. I noticed recently whenever we merge the PR on the master it runs our test again as we have that in our workflow. I think we should remove the push section as the tests are running in redundantly after the merge.  And add the paths-ignore in the pull section. 
^^ @ricardozanini @LCaparelli wdyt?

**Comment by LCaparelli** [comment]
Sounds good to me @Kaitou786

**Comment by ricardozanini** [comment]
@Kaitou786 are you going to send a PR to make these changes?

**Comment by Kaitou786** [comment]
> @Kaitou786 are you going to send a PR to make these changes?

Added the commit as the part of this one only :-)

**Pull request merged**
