### PR TITLE
Enable golint linter in golangci-lint

### PR DESCRIPTION
**Pull request by Kaitou786**
Enabled the golint linter to run with golangci-lint.
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

### CODE REVIEW

**Comment by Kaitou786** [comment]
@ricardozanini I just added the another package to call the functions instead of `resource.go` . I think it is preferred for a parent package to not call functions from its child package, So I created a sibling package and did these things and only left the parent package with the interfaces. But yes it can be in a same package

**Comment by ricardozanini** [comment]
@Kaitou786 understood! Let's wait for @LCaparelli, I believe he will fix this in his PR #87. Then we can rebase and merge this one. :)

**Comment by ricardozanini** [comment]
@LCaparelli from the client perspective (`NexusController`) how it will be? `deployment.NewManager()`? Or `resources.New()` (all managers)? 

I'm not sure if I like the name `interfaces`, we could use `infra` instead. Plus, it's not a good practice having packages in plural, so I'd say to also rename `resources` to `resource`.

**Comment by LCaparelli** [comment]
> @LCaparelli from the client perspective (`NexusController`) how it will be? `deployment.NewManager()`? Or `resources.New()` (all managers)?

That would be left unchanged, the clients would still instantiate the `NexusResourceManager` (or `Supervisor`), which would in turn instantiate the Managers via their respective package, such as `deployment.NewManager`.

Someone using the API could also instantiate the Managers separately, without the need for a Supervisor, by running `deployment.NewManager` or `networking.NewManager` (or whichever manager) directly.

Anyone using either the Managers or the Supervisor would still need to import `interface` though, in order to manipulate these structs. 

> I'm not sure if I like the name `interfaces`, we could use `infra` instead.

I agree that `interface` could also carry more meaning. I'm still not sure if there isn't some other name we could use that is more significant, but I'm definitely ok with `infra` as well.

> Plus, it's not a good practice having packages in plural, so I'd say to also rename `resources` to `resource`.

Agreed :+1:

**Comment by Kaitou786** [comment]
@ricardozanini @LCaparelli do we want to make these changes as a part of this PR, or as a part of PR #87 ?

**Comment by ricardozanini** [comment]
> @ricardozanini @LCaparelli do we want to make these changes as a part of this PR, or as a part of PR #87 ?

@Kaitou786 I think @LCaparelli forgot to mention, he's working on a new PR to fix those, so we can later rebase this one and merge it. Probably tomorrow on your TZ. :)

We will let you know during your sleep :p

**Comment by LCaparelli** [comment]
@Kaitou786 I think this would be a better fit for a new PR altogether, I'll send it today. Once we merge that we can rebase it for this and #87. This way each of our PRs only solve one issue :-)

**Comment by Kaitou786** [comment]
Ah okay, thank you guys =D

**Comment by LCaparelli** [comment]
Depends on #90

**Comment by ricardozanini** [comment]
@Kaitou786 just rebase and let's be happy. :D

**Comment by Kaitou786** [comment]
@LCaparelli exposed the `fakeDiscBuilder` and it fixed all, thanks :D

**Pull request merged**
